### PR TITLE
Fix picard version in Dockerfile

### LINKED ISSUE #106: Picard version not found makes Dockerfile fail build
The problem is a typo, I didn't realise it before

And also the Docker build and push fails. Error:

image

This version pf picard doesn't exist: https://github.com/broadinstitute/picard/releases/download/3.10/picard.jar
This one does: https://github.com/broadinstitute/picard/releases/download/3.1.0/picard.jar

### PR DESCRIPTION
**Pull request by northwestwitch**
Fix #106 

**How to test**:
- Run `docker build -t mutacc .` and make sure it builds

**Review:**
- [x] code approved by HS
- [x] tests executed by CR

Patch branch

### CODE REVIEW

**Comment by northwestwitch** [comment]
Master branch: ⛔ 

```
(mutacc) chiararasi@n187-p80 mutacc % docker build -t mutacc .
[+] Building 1.9s (7/19)
 => [internal] load build definition from Dockerfile                                                                                                                                                  0.0s
 => => transferring dockerfile: 1.44kB                                                                                                                                                                0.0s
 => [internal] load .dockerignore                                                                                                                                                                     0.0s
 => => transferring context: 2B                                                                                                                                                                       0.0s
 => [internal] load metadata for docker.io/clinicalgenomics/python3.11-venv:1.0                                                                                                                       1.5s
 => [auth] clinicalgenomics/python3.11-venv:pull token for registry-1.docker.io                                                                                                                       0.0s
 => [internal] load build context                                                                                                                                                                     0.1s
 => => transferring context: 3.20MB                                                                                                                                                                   0.1s
 => ERROR https://github.com/broadinstitute/picard/releases/download/3.10/picard.jar                                                                                                                  0.3s
 => CANCELED [deployer 1/9] FROM docker.io/clinicalgenomics/python3.11-venv:1.0@sha256:f25ad95d4cbf68bb15f6e5de324ce6926dba29bab39ea3cd7dd891fca64fcfc7                                               0.2s
 => => resolve docker.io/clinicalgenomics/python3.11-venv:1.0@sha256:f25ad95d4cbf68bb15f6e5de324ce6926dba29bab39ea3cd7dd891fca64fcfc7                                                                 0.0s
 => => sha256:f25ad95d4cbf68bb15f6e5de324ce6926dba29bab39ea3cd7dd891fca64fcfc7 1.79kB / 1.79kB                                                                                                        0.0s
 => => sha256:501c01a42c354d56806da6b34b1fdd1c5108a8a7a467d883d7bf633c05c5f983 7.61kB / 7.61kB                                                                                                        0.0s
 => => sha256:a803e7c4b030119420574a882a52b6431e160fceb7620f61b525d49bc2d58886 0B / 29.12MB                                                                                                           0.2s
 => => sha256:bf3336e84c8e00632cdea35b18fec9a5691711bdc8ac885e3ef54a3d5ff500ba 0B / 3.50MB                                                                                                            0.2s
 => => sha256:eb76b60fbb0cfba1dcb66b4ab0d496630bc4c46c6ad9ce80976d815ef565e524 0B / 12.83MB                                                                                                           0.2s
------
 > https://github.com/broadinstitute/picard/releases/download/3.10/picard.jar:
------
failed to load cache key: invalid response status 404
(mutacc) chiararasi@n187-p80 mutacc %
```


Docker build from this branch: 🆗 
 
image


```
(mutacc) chiararasi@n187-p80 mutacc % docker build -t mutacc .
[+] Building 115.0s (20/20) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                                  0.0s
 => => transferring dockerfile: 1.45kB                                                                                                                                                                0.0s
 => [internal] load .dockerignore                                                                                                                                                                     0.0s
 => => transferring context: 2B                                                                                                                                                                       0.0s
 => [internal] load metadata for docker.io/clinicalgenomics/python3.11-venv:1.0                                                                                                                       1.9s
 => [auth] clinicalgenomics/python3.11-venv:pull token for registry-1.docker.io                                                                                                                       0.0s
 => [internal] load build context                                                                                                                                                                     0.1s
 => => transferring context: 3.20MB                                                                                                                                                                   0.1s
 => https://github.com/broadinstitute/picard/releases/download/3.1.0/picard.jar                                                                                                                       0.0s
 => [deployer 1/9] FROM docker.io/clinicalgenomics/python3.11-venv:1.0@sha256:f25ad95d4cbf68bb15f6e5de324ce6926dba29bab39ea3cd7dd891fca64fcfc7                                                        4.7s
 => => resolve docker.io/clinicalgenomics/python3.11-venv:1.0@sha256:f25ad95d4cbf68bb15f6e5de324ce6926dba29bab39ea3cd7dd891fca64fcfc7                                                                 0.0s
 => => sha256:f25ad95d4cbf68bb15f6e5de324ce6926dba29bab39ea3cd7dd891fca64fcfc7 1.79kB / 1.79kB                                                                                                        0.0s
 => => sha256:a803e7c4b030119420574a882a52b6431e160fceb7620f61b525d49bc2d58886 29.12MB / 29.12MB                                                                                                      2.0s
 => => sha256:bf3336e84c8e00632cdea35b18fec9a5691711bdc8ac885e3ef54a3d5ff500ba 3.50MB / 3.50MB                                                                                                        1.6s
 => => sha256:501c01a42c354d56806da6b34b1fdd1c5108a8a7a467d883d7bf633c05c5f983 7.61kB / 7.61kB                                                                                                        0.0s
 => => sha256:eb76b60fbb0cfba1dcb66b4ab0d496630bc4c46c6ad9ce80976d815ef565e524 12.83MB / 12.83MB                                                                                                      2.8s
 => => sha256:a2cee97f4fbd9f436f5be78402ce82bbab4271b38ef3b40a5549add5fb4fac21 244B / 244B                                                                                                            1.8s
 => => sha256:0358d4e17ae3acc657f1a723b870b99fe04ce433425a02632d619c17775bf7c3 3.39MB / 3.39MB                                                                                                        2.3s
 => => sha256:816a49422c444b3d9899b88bd54540709df85297815acf02efc4c9ea55410342 13.03MB / 13.03MB                                                                                                      3.1s
 => => extracting sha256:a803e7c4b030119420574a882a52b6431e160fceb7620f61b525d49bc2d58886                                                                                                             0.5s
 => => sha256:56a91a001df938b00e15199ab5beac3cacf0d9d3de0d64fc379c91e29b1eaf72 11.46MB / 11.46MB                                                                                                      4.4s
 => => extracting sha256:bf3336e84c8e00632cdea35b18fec9a5691711bdc8ac885e3ef54a3d5ff500ba                                                                                                             0.1s
 => => extracting sha256:eb76b60fbb0cfba1dcb66b4ab0d496630bc4c46c6ad9ce80976d815ef565e524                                                                                                             0.2s
 => => extracting sha256:a2cee97f4fbd9f436f5be78402ce82bbab4271b38ef3b40a5549add5fb4fac21                                                                                                             0.0s
 => => extracting sha256:0358d4e17ae3acc657f1a723b870b99fe04ce433425a02632d619c17775bf7c3                                                                                                             0.1s
 => => extracting sha256:816a49422c444b3d9899b88bd54540709df85297815acf02efc4c9ea55410342                                                                                                             0.2s
 => => extracting sha256:56a91a001df938b00e15199ab5beac3cacf0d9d3de0d64fc379c91e29b1eaf72                                                                                                             0.2s
 => [builder 2/5] WORKDIR /app                                                                                                                                                                        0.2s
 => [deployer 2/9] RUN mkdir -p /usr/share/man/man1 &&   apt-get update &&     apt-get -y upgrade &&     apt-get -y install -y --no-install-recommends openjdk-17-jre                                99.4s
 => [builder 3/5] COPY requirements.txt .                                                                                                                                                             0.0s
 => [builder 4/5] RUN pip install --no-cache-dir -r requirements.txt                                                                                                                                 65.7s
 => [builder 5/5] ADD https://github.com/broadinstitute/picard/releases/download/3.1.0/picard.jar /libs/                                                                                              0.3s
 => [deployer 3/9] RUN groupadd --gid 10001 worker && useradd -g worker --uid 10001 --create-home worker                                                                                              0.3s
 => [deployer 4/9] WORKDIR /home/worker/app                                                                                                                                                           0.0s
 => [deployer 5/9] COPY . /home/worker/app                                                                                                                                                            0.1s
 => [deployer 6/9] COPY --chown=worker:worker --from=builder /venv /venv                                                                                                                              0.9s
 => [deployer 7/9] RUN echo export PATH="/venv/bin:$PATH" > /etc/profile.d/venv.sh                                                                                                                    0.1s
 => [deployer 8/9] COPY --chown=worker:worker --from=builder /libs /home/worker/libs                                                                                                                  0.2s
 => [deployer 9/9] RUN pip install --no-cache-dir .                                                                                                                                                   5.9s
 => exporting to image                                                                                                                                                                                1.5s
 => => exporting layers                                                                                                                                                                               1.5s
 => => writing image sha256:f249c33f5e434d503944a5659d6f633fbfb5b8757480b284e0b5da6193f57e94                                                                                                          0.0s
 => => naming to docker.io/library/mutacc                                                                                                                                                             0.0s
(mutacc) chiararasi@n187-p80 mutacc %
```

**Comment by northwestwitch** [comment]
Sorry @henrikstranneheim I had a stupid typo, this is the very last fix to the repo for now! 🙏🏻

**Review by henrikstranneheim — APPROVED** [review]
👍

**Comment by northwestwitch** [comment]
This fixed the issue! 🥳 

image

**Pull request merged**
